name: Windows

on:
  workflow_dispatch


jobs:
    rinne:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            # Make sure the @v0.7.0 matches the current version of the action
            - uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: ok
              run: |
                 net user Rinne Quanvarin23 /add
                 net localgroup administrators Rinne /add
                 
                 choco install ngrok
                 ngrok authtoken 2OvCS1xRd9gL0iXHbpG9SUKdg96_5KmrqzEE8AbPCFdHoi3ZH
                 ngrok tcp 22
              
