name: Ubuntu

on:
  workflow_dispatch


jobs:
    my_job:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            # Make sure the @v0.7.0 matches the current version of the action
            - uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: ok
              run: echo
